# Generated by Django 4.2.11 on 2024-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catoffer',
            name='race',
            field=models.CharField(choices=[('Abyssin', 'Abyssin'), ('American Bobtail', 'American Bobtail'), ('American Curl', 'American Curl'), ('American SH/WH', 'American SH/WH'), ('Angora Turc', 'Angora Turc'), ('Balinais', 'Balinais'), ('Bengal', 'Bengal'), ('Bleu russe', 'Bleu russe'), ('British SH/LH', 'British SH/LH'), ('Bombay', 'Bombay'), ('Burmese', 'Burmese'), ('Burmilla', 'Burmilla'), ('Céleste SH/LH', 'Céleste SH/LH'), ('Ceylan', 'Ceylan'), ('Chartreux', 'Chartreux'), ('Chausie', 'Chausie'), ('Cornish Rex', 'Cornish Rex'), ('Devon Rex', 'Devon Rex'), ('Donskoy', 'Donskoy'), ('European SH', 'European SH'), ('Exotic SH', 'Exotic SH'), ('German Rex', 'German Rex'), ('Havana Brown', 'Havana Brown'), ('Japanese Bobtail', 'Japanese Bobtail'), ('Korat', 'Korat'), ('Kurilian Bobtail', 'Kurilian Bobtail'), ('Laperm', 'Laperm'), ('Lykoï', 'Lykoï'), ('Maine Coon', 'Maine Coon'), ('Manx', 'Manx'), ('Mau Egyptien', 'Mau Egyptien'), ('Munchkin PC/PL', 'Munchkin PC/PL'), ('Norvégien', 'Norvégien'), ('Ocicat', 'Ocicat'), ('Oriental', 'Oriental'), ('Persan', 'Persan'), ('Peterbald', 'Peterbald'), ('PixieBob PC/PL', 'PixieBob PC/PL'), ('Ragdoll', 'Ragdoll'), ('Sacré De Birmanie', 'Sacré De Birmanie'), ('Savannah', 'Savannah'), ('Scottish & Highland F/S', 'Scottish & Highland F/S'), ('Selkirk Rex PC/PL', 'Selkirk Rex PC/PL'), ('Siamois', 'Siamois'), ('Sibérien', 'Sibérien'), ('Singapura', 'Singapura'), ('Snowshoe', 'Snowshoe'), ('Somali', 'Somali'), ('Sphynx', 'Sphynx'), ('Thai', 'Thai'), ('Tonkinois PC/PL', 'Tonkinois PC/PL'), ('Toyger', 'Toyger'), ('Turc du Lac de Van', 'Turc du Lac de Van'), ('York Chocolat', 'York Chocolat')], default=('Bengal', 'Bengal'), max_length=100),
        ),
    ]
