# Generated by Django 4.2.11 on 2024-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_catoffer_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='catoffer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cat_offer_pictures/'),
        ),
    ]
