# Generated by Django 4.2.11 on 2024-03-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_catoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
