# Generated by Django 4.2.11 on 2024-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_catoffer_picture2_catoffer_picture3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catoffer',
            name='sex',
            field=models.CharField(choices=[('Male', 'Mâle'), ('Female', 'Femelle')], max_length=20),
        ),
    ]
