# Generated by Django 4.2.11 on 2024-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_catoffer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catoffer',
            name='sex',
            field=models.CharField(choices=[('Mâle', 'Mâle'), ('Femelle', 'Femelle')], max_length=20),
        ),
    ]
