# Generated by Django 4.2.11 on 2024-04-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_catoffer_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catoffer',
            old_name='owner',
            new_name='user',
        ),
    ]
