# Generated by Django 4.2.11 on 2024-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_catoffer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catoffer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7),
        ),
    ]
