# Generated by Django 4.2.11 on 2024-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_alter_catoffer_eye_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catoffer',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('Bleus', 'Bleus'), ('Verts', 'Verts'), ('Or', 'Or'), ('Vairons', 'Vairons')], default=None, max_length=100),
        ),
    ]
