# Generated by Django 4.2.11 on 2024-05-04 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_alter_catoffer_eye_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catoffer',
            name='id_num',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
