const users = [
  {
    id: 1,
    name: "Cristina",
    image: "../assets/images/people/Cristina.jpg",
    email: "cristina@email.com",
    presentation: "Eleveuse de bengal depuis 3 ans, je propose mon mâle pour quelques saillies extérieures",
    website: "http://lesbengaldemplates.com",
    facebook: "https://www.facebook.com/cristina.lemat",
    birthday: "22/05/1994",
  },
  {
    id: 2,
    name: "Gertrude",
    image: "../assets/images/people/Gertrude.jpg",
    email: "Gertrude@email.com",
    presentation: "Eleveuse de sphynx depuis peu, je un mâle pour ma femelle",
    website: "http://lessphynxdelahoue.com",
    facebook: "https://www.facebook.com/Gertrude.lecap",
    birthday: "14/08/1990",
  },
  {
    id: 3,
    name: "Paul",
    image: "../assets/images/people/Paul.jpg",
    email: "Paul@email.com",
    presentation: "Eleveur professionnel de Ragdoll",
    website: "http://www.eleveur-ragdoll.com",
    facebook: "https://www.facebook.com/Paul.daim",
    birthday: "28/12/1997",
  },
  {
    id: 4,
    name: "Suzanne",
    image: "../assets/images/people/suzanne.jpg",
    email: "Suzanne@gmail.com",
    presentation: "Eleveuse professionnelle d'Abyssin.",
    website: "http://abyssinsdesbois.com",
    facebook: "https://www.facebook.com/Suzanne.desbois",
    birthday: "22/05/1994",
  },
  {
    id: 5,
    name: "Warren",
    image: "../assets/images/people/warren.jpg",
    email: "Warren@email.com",
    presentation: "",
    website: "",
    facebook: "",
    birthday: "",
  },
];
