# Generated by Django 4.2.11 on 2024-04-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_alter_catoffer_eye_color'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cat_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.catoffer'),
        ),
    ]
