# Generated by Django 4.2.11 on 2024-04-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
